---
# tasks file for git
- name: install git
  package:
    name: "{{ git_packages }}"
    state: "{{ git_package_state }}"
  register: git_install_git
  until: git_install_git is succeeded
  retries: 3
